---
title: "Exploratory Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(ggridges)
```


```{r include=FALSE}
inspection_sub<-read.csv("data/inspection_sub.csv") %>% 
  janitor::clean_names() %>% 
  select(-boro_y,-building_y,-street_y,-zipcode_y,-location_point,-dba_y,-url,-phone) %>% 
  rename(dba=dba_x,boro=boro_x,building=building_x,street=street_x,zipcode=zipcode_x) %>%
  select(dba,boro,cuisine_description,critical_flag,score,grade,grade_date,inspection_type,latitude,longitude,rating,review_num,price) 
  
```

## boro vs cuisine
```{r echo = FALSE}
boro_cuisine_bar<-
inspection_sub %>% 
  select(dba,boro,cuisine_description,critical_flag,score,grade,grade_date,inspection_type,latitude,longitude,rating,review_num,price) %>%
  drop_na(boro) %>% 
  mutate(cuisine_description=fct_infreq(cuisine_description)) %>% 
  group_by(boro,cuisine_description) %>%
  summarize(n_obs=n()) %>% 
  filter(min_rank(desc(n_obs)) <= 10) %>%
  ggplot(aes(x=cuisine_description,y=n_obs,fill=cuisine_description))+
  geom_bar(position="dodge", stat="identity")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  theme(axis.text.x = element_text(size = 5))+
  labs(
    x="Cuisine type",
    y="Number")+
  facet_grid(~boro)

ggplotly(boro_cuisine_bar)
```
## price vs cuisine
```{r}

```



## Xuesen 

```{r}
inspection_sub = read.csv("data/inspection_sub.csv") %>% 
  janitor::clean_names() %>% 
  select(-boro_y,-building_y,-street_y,-zipcode_y,-location_point,-dba_y,-url,-phone) %>% 
  rename(dba=dba_x,boro=boro_x,building=building_x,street=street_x,zipcode=zipcode_x) %>%
  replace_na(list(grade = "N"))

inspection_raw = read_csv("./data/inspection_sub_all_date.csv") %>%
  janitor::clean_names() %>%
  mutate(
    violation_description = as.factor(violation_description)
  )
  
top_10_vio = inspection_raw %>% 
  group_by(violation_description) %>%
  summarize(
    n = n()
  ) %>%
  mutate(
    rank = rank(-n, ties.method = "first")
  ) %>% 
  filter(rank <=10) %>%
  arrange(desc(n)) %>% mutate(
    rank = as.factor(rank)
  ) %>%
  mutate(
    abb_violation = fct_recode(
      rank,
      "Non-food contact surface improperly constructed" = "1",
      "Food contact surface not properly cleaned" = "2",
      "Unacceptable materials" = "3",
      "Facility not vermin proof" = "4", 
      "Not free of harborage" = "5",
      "Evidence of mice or live mice present" = "6",
      "Filth flies or food/refuse/sewage with FRSA  flies"  = "7",
      "Cold CT food held above 41 F" = "8",
      "Cold food item held above 41 F" = "9",
     "Evidence of mice or live mice in establishment’s food or non-food areas" = "10"
        )
  )



top_10_vio %>%
  ggplot(aes(x = rank, y = n, fill = n), data = .)+geom_bar(stat="identity")+labs(x = "violation type", y = "frequency", caption = "Exact violation type and associated frquency is shown in the following table")
  
top_10_vio %>% 
  select(abb_violation, n) %>%
  knitr::kable()
```

```{r}
## Yelp Rating vs. price boxplot 
inspection_sub %>% 
  filter(!is.na(price)) %>%
  ggplot(aes(x = price, y = rating, fill = price), data = .)+geom_boxplot()+labs(title = "Yelp Rating vs. Price")
```

```{r}
inspection_sub %>%
  filter(!is.na(grade),!is.na(boro)) %>%
  ggplot(aes(x = boro, y = grade, fill = grade), data =.) + geom_bar(stat = "identity", position="stack") + labs(title = "Inspection grade by Boroughs")
```

```{r}
inspection_sub %>%
  filter(!is.na(grade),!is.na(boro)) %>%
  filter(critical_flag == c("Critical", "Not Critical")) %>%
  ggplot(aes(x = boro, y = critical_flag, fill = critical_flag), data =.) + geom_bar(stat = "identity", position="stack") + labs(title = "Percent with critical flag by boroughs")
```

