---
title: "Restaurant Recommender"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(rmarkdown)
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(viridis)

library(shiny)
library(shinyWidgets)
library(jsonlite)
library(geosphere)
library(urltools)
library(leaflet)
library(DT)

```

```{r golbal, context = "data"}

all_res_df = read_csv("shiny_data/inspection_sub_all_date.csv") %>%
  nest(inspection_detail = action:critical_flag) %>% 
  mutate(price_count = str_count(price, fixed("$")))

latest_res_df = read_csv("shiny_data/inspection_sub_latest_date.csv") %>%
  nest(inspection_detail = action:critical_flag)%>% 
  mutate(price_count = str_count(price, fixed("$"))) %>% 
  drop_na()

cuisine_list = 
  all_res_df %>% 
  select(cuisine_description) %>% 
  count(cuisine_description) %>% 
  arrange(desc(n)) %>% 
  slice(1:10) %>% 
  select(cuisine_description) %>% 
  add_row(cuisine_description = "Others") %>%
  pull()

price_list = c(
  "$ <10",
  "$$ 10-30",
  "$$$ 31-60",
  "$$$$ >60"
)

```

User Input {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r user_input}
selectInput(
  inputId = "boro_choice",
  label = "Select borough",
  choices = all_res_df %>% distinct(boro) %>% pull(), 
  selected  = "Manhattan"
)

textInput(
  inputId = "street", 
  label = "Street (Optional)")

selectInput(
  inputId = "cuisince_choice",
  label = "Select cuisine type", 
  choice = cuisine_list
)

sliderInput(
  inputId = "rating_range",
  label = "Choose rating range",
  min = 0.0, max = 5.0, value = c(3.5, 5.0), step = 0.1, round = -2
)

sliderTextInput(
  inputId = "price_range",
  label = "Choose price range" , 
  choices = price_list, 
  selected = c(price_list[2], price_list[4])
)

sliderInput(
  "inspection_range",
  label = "Choose inspection score range",
  min = 0, max = 100, value = c(0, 100)
)

actionButton(
  "search_button", "Search"
)
```

Column {data-width= 650}
-----------------------------------------------------------------------

### Result

```{r}
get_coord <- function(url, boro) {
  
  tryCatch({
    coord =  fromJSON(url(url))$features %>% 
      tibble() %>% 
      filter(properties$borough == boro) %>% 
      slice(1,) %>% 
      select(geometry) %>% unlist() %>% 
      as.vector() %>% .[2:3] %>% 
      as.double() %>% c()
    return(ifelse(is.na(coord), c(0, 0), coord))
  }, 
  
  error=function(e){
    return(c(0, 0))
  })
  
}

target_coord = eventReactive(
  input$search_button, 
  get_coord(paste0("https://geosearch.planninglabs.nyc/v1/search?text=", url_encode(input$street)), input$boro_choice)
)

get_dist <- function(coord1, coord2) {
  dist = ifelse(coord1 == c(0, 0), NA , round(distm(coord1, coord2, fun = distHaversine)[,1]/1609, digits = 1)[1])
  dist = as.vector(dist)[1]
  return(dist)
}

res_df = 
  eventReactive(
    input$search_button,
    latest_res_df  %>% 
    filter(boro == input$boro_choice, 
      cuisine_description ==  input$cuisince_choice, 
      rating %in% seq(input[["rating_range"]][1],input[["rating_range"]][2],0.1),
      price_count %in% str_count(input$price_range[1],fixed("$")):str_count(input$price_range[2], fixed("$")), 
      score %in% input$inspection_range[1]:input$inspection_range[2])%>% 
      mutate(
        coord = map2(longitude, latitude, ~c(.x, .y)), 
        distance = map(coord, ~get_dist(target_coord(), .x)), 
        info = str_c(dba, " (", rating,", ", price,  ")\n", building, " ", street)) %>% 
      unnest(distance) %>% 
      arrange(desc(rating))
)
 

output$res_table = renderDataTable(
  datatable(res_df() %>%
    select(dba, building, street, rating, price, score, distance) %>% 
    rename(name = dba, inspection = score) ,
      options = list(
        scrollX = TRUE,
        scrollY = "500px"
      ), selection = "single")
)

dataTableOutput("res_table")

```

Column {data-width=400}
-----------------------------------------------------------------------

### Map

```{r}
res_map =
  eventReactive(
    input$search_button,
    latest_res_df  %>%
    filter(boro == input$boro_choice,
      cuisine_description ==  input$cuisince_choice,
      rating %in% seq(input[["rating_range"]][1],input[["rating_range"]][2],0.1),
      price_count %in% str_count(input$price_range[1],fixed("$")):str_count(input$price_range[2], fixed("$")),
      score %in% input$inspection_range[1]:input$inspection_range[2])%>%
      mutate(
        coord = map2(longitude, latitude, ~c(.x, .y)),
        distance = map(coord, ~get_dist(target_coord(), .x)),
        info = str_c(dba, " (", rating,", ", price,  ")\n", building, " ", street)
        )
)


output$leaflet = renderLeaflet({
 
    leaflet(res_map()) %>%
    addTiles() %>% 
    addCircleMarkers(lng=~longitude, lat=~latitude, label = ~dba, popup=~ info, radius = 3, color = "red", fillOpacity = ~rating)
  })

leafletOutput("leaflet")

```

### Inspection Records

```{r}
# input$res_table_cell_clicked

output$ins_table = renderTable({
  req(length(input$res_table_cell_clicked) > 0)
  res_df() %>% slice(input$res_table_cell_clicked$row, ) %>% 
    unnest(inspection_detail) %>% 
    mutate(inspection_date = format(inspection_date,'%Y-%m-%d'), 
           score = as.integer(score)) %>% 
    select(violation_code, violation_description, critical_flag, inspection_date, inspection_type, score, grade)}, width = "10%")

tableOutput("ins_table")

```